# Generated by Django 4.2.7 on 2024-01-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='adderss',
            field=models.TextField(default='Bangalore'),
            preserve_default=False,
        ),
    ]
